title: "CV - A hub of work profiles showcase your skills, experience, achievements"
description: "Create a comprehensive work profile by building a secure online CV hub. Showcase your professional achievements, skills, and career goals."
url: "https://cv.wikimint.com"

permalink: /:title

paginate: 5
paginate_path: "/page/:num/"


include:
  - ".htaccess"

timezone: "America/New_York"

